name: Deploy latest version to Github Releases

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Dotnet Publish
        run: |
          dotnet publish src/Unispect/Unispect.csproj \
            -c Release \
            -r win-x64 \
            --no-self-contained \
            /p:PublishSingleFile=true \
            /p:DebugType=none \
            /p:EnableWindowsTargeting=true \
            -o out

      - name: Archive publish output
        run: |
          cd out
          zip -r ../UnispectEx.zip .

      - name: Upload to "latest" release (overwrite old asset)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload latest UnispectEx.zip --clobber
